/sensor/lidar/top/points:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10

/sensor/lidar/front/points:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10

/sensor/lidar/left/points:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10

/sensor/lidar/right/points:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10

/sensor/imu/front/data:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 200
